<?php /** @var $block Pap\OrderNote\Block\Adminhtml\Order\View\Note */ ?>
<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title">Order Shipping note</span>
    </div>
    <div class="admin__page-section-content">
        <table class="admin__table-secondary order-information-table">
            <tbody>
                <tr>
                    <th><?php echo $block->getCurrentNote(); ?></th>
                </tr>
            </tbody>
        </table>
    </div>
</section>